# Site settings
title: "Jadob Framework"
description: > 
  PHP 7 Framework.
baseurl: "/"
url: "https://jadob.github.io/"

permalink: /:year/:month/:title

collections:
  - components

markdown: kramdown

highlighter: rouge
kramdown:
  input: GFM